

/* The Fibonacci numbers are generated by setting F0 = 0, F1 = 1, 
and then using the recursive formula. Fn = Fn-1 + Fn-2. to get the rest. 
Thus the sequence begins: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, … 
This sequence of Fibonacci numbers arises all over mathematics and also in nature.
*/
package program;
public class fibonacci_series {
    public static void main(String[] args) {
        int i=0,k,j=1;
        int n=10; //count for no. in the series
        int a = 2; //start point for n
        System.out.println(i+ "\n" +j);
        while(a<=n){
            k=j+i; // fn= fn-1 + fn-2
            System.out.println(k); 
            i=j;
            j=k;
            a++;
        }
        
    }
}
